# Generated by Django 4.2.2 on 2023-08-05 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Becomeadeveloper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('skills', models.CharField(choices=[('Front-End Development, 6 months, ₦45,000', 'Front-End Development, 6 months, ₦45,000'), ('Back-End Development, 6 months, ₦50,000', 'Back-End Development, 6 months, ₦50,000'), ('Full-Stack Development, 12 months, ₦85,000', 'Full-Stack Development, 12 months, ₦85,000'), ('Computer Hardware Engineering, 9 months, ₦60,000', 'Computer Hardware Engineering, 9 months, ₦60,000'), ('Data Analysis, 8 months, ₦70,000', 'Data Analysis, 8 months, ₦70,000')], default='Front-End Development, 6 months, ₦45,000', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.CharField(max_length=300)),
            ],
        ),
    ]
